### PR TITLE
Add component diagram

### PR DESCRIPTION
**Pull request by dwinchell**

### CODE REVIEW

**Review by gfulton-redhat — COMMENTED** [review]
@dwinchell you may want to consider breaking the single diagram up into individual concerns to address a single unit of work ie.. person uses helm to install secret(s)

**Comment by dwinchell** [comment]
@twling @gfulton-redhat Is this more clear?

I want to add some text to explain the diagrams, but I'm hoping they also convey most of their meaning on their own.

**Review by gfulton-redhat — COMMENTED** [review]
[@aarongreen85 ]
@dwinchell you may want to consider the following to make the diagram easier to follow.

- Removing the words `Database and Container` just call it a `Git Repository` on both diagrams.
- Remove the word `Database` when referencing `Volume Mounts` on both diagrams.
- Remove references to pligos-github-workflow and java-github-example on infrastructure deployment diagram.
- Remove references pligos-github-runner image, github-runners, infra-ops, and openshift-actions-runner-chart on the workflow execution diagram

[@gfulton-redhat ]
@dwinchell you may want to consider adding notes or a paragh to give the reader some context.

**Comment by dwinchell** [comment]
> [@aarongreen85 ] @dwinchell you may want to consider the following to make the diagram easier to follow.
> 
> * Removing the words `Database and Container` just call it a `Git Repository` on both diagrams.
> * Remove the word `Database` when referencing `Volume Mounts` on both diagrams.
> * Remove references to pligos-github-workflow and java-github-example on infrastructure deployment diagram.
> * Remove references pligos-github-runner image, github-runners, infra-ops, and openshift-actions-runner-chart on the workflow execution diagram
> 
> [@gfulton-redhat ] @dwinchell you may want to consider adding notes or a paragh to give the reader some context.

The Database/Container labels are because the diagram uses c4 notation. Check out https://c4model.com/ if you're interested.

I can see the rationale for deleting things that aren't touched by an arrow. I want at least one diagram that shows everything we created though. Instead i updated the diagrams to make them exactly the same except arrows. That should help make it clearer that some stuff is intentionally shown even though it is not used in a specific workflow.

**Pull request merged**
